### ISSUE TITLE
Why the "derive" crate?

### ISSUE THREAD

**Issue by Janonard** [rust-dsp/rust-lv2#1]
Why is there a separate `derive` crate for macros and why aren't these macros included in the "main" crate?

I mean, it includes very few code and it is only useful together with the "main" crate. Also, having an additional crate introduces additional complexity and we have to reserve yet another crate name.

So, what were your initial reasons to move the macros to a separate crate?

**Comment by prokopyl** [comment]
Procedural macros are required to be in their own crate by the Rust compiler, so there's not much to do about it.
Though I think it makes sense as it is, as this code is ran by the compiler at build time (unlike the library), and has dependencies that are only used on the build step (and never included in the final binary).

Also, the fact that it is a separate crate does not really introduce additional complexity for the user, as they are re-exported by the main crate anyways (something many crates like serde now do):
https://github.com/rust-dsp/rust-lv2/blob/17ead6ca6de9a50997a9eaae51e97278e6b67178/lv2-core/src/plugin.rs#L9

And with the 2018 edition, those macros are imported like any other trait and function, so it feels even nicer to use: 
https://github.com/rust-dsp/rust-lv2/blob/17ead6ca6de9a50997a9eaae51e97278e6b67178/lv2/examples/amplifier/lib.rs#L2

**Comment by Janonard** [comment]
Okay, fair enough! :smiley:
